In [4]:
%pip install "setuptools<82"
%pip install PyTDC

Collecting setuptools<82
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 13.9 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 84.0.0
    Uninstalling setuptools-84.0.0:
      Successfully uninstalled setuptools-84.0.0
Successfully installed setuptools-81.0.0
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: PyTDC in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (1.0.0)
Requirement already satisfied: biopython<2.0,>=1.78 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (1.88)
Requirement already satisfied: dataclasses<1.0,>=0.6 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (0.6)
Requirement already satisfied: fuzzywuzzy<1.0,>=0.18.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (0.18.0)
Requirement already satisfied: huggingface_hub<1.0,>=0.20.3 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (0.36.2)
Requirement already satisfied: mygene<4.0.0,>=3.2.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (3.2.2)
Requirement already satisfied: numpy<2.0.0,>=1.26.4 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (1.26.4)
Requirement already satisfied: openpyxl<4.0.0,>=3.0.10 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (3.1.5)
Requirement already satisfied: pandas<3.0.0,>=2.1.4 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (2.3.3)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (2.34.2)
Requirement already satisfied: scikit-learn==1.2.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (1.2.2)
Requirement already satisfied: seaborn<1.0.0,>=0.12.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (0.13.2)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (4.70.1)
Requirement already satisfied: cellxgene-census<2.0.0,>=1.10.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (1.18.0)
Requirement already satisfied: gget<1.0.0,>=0.28.4 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (0.30.8)
Requirement already satisfied: pydantic<3.0.0,>=2.6.3 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (2.13.5)
Requirement already satisfied: rdkit<2024.3.1,>=2023.9.5 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (2023.9.6)
Requirement already satisfied: tiledbsoma<2.0.0,>=1.7.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (1.17.1)
Requirement already satisfied: yapf<1.0.0,>=0.40.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from PyTDC) (0.43.0)
Requirement already satisfied: scipy>=1.3.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scikit-learn==1.2.2->PyTDC) (1.17.1)
Requirement already satisfied: joblib>=1.1.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scikit-learn==1.2.2->PyTDC) (1.6.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scikit-learn==1.2.2->PyTDC) (3.7.0)
Requirement already satisfied: anndata in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from cellxgene-census<2.0.0,>=1.10.2->PyTDC) (0.12.19)
Requirement already satisfied: typing_extensions in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from cellxgene-census<2.0.0,>=1.10.2->PyTDC) (4.16.0)
Requirement already satisfied: s3fs>=2021.06.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from cellxgene-census<2.0.0,>=1.10.2->PyTDC) (2026.9.0)
Requirement already satisfied: beautifulsoup4>=4.10 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from gget<1.0.0,>=0.28.4->PyTDC) (4.15.0)
Requirement already satisfied: ipython in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from gget<1.0.0,>=0.28.4->PyTDC) (9.17.1)
Requirement already satisfied: ipywidgets in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from gget<1.0.0,>=0.28.4->PyTDC) (8.1.9)
Requirement already satisfied: lxml in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from gget<1.0.0,>=0.28.4->PyTDC) (6.1.3)
Requirement already satisfied: matplotlib in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from gget<1.0.0,>=0.28.4->PyTDC) (3.11.2)
Requirement already satisfied: mysql-connector-python>=8.0.32 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from gget<1.0.0,>=0.28.4->PyTDC) (26.7.0)
Requirement already satisfied: filelock in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.20.3->PyTDC) (4.0.12)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.20.3->PyTDC) (2026.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.20.3->PyTDC) (1.7.0)
Requirement already satisfied: packaging>=20.9 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.20.3->PyTDC) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.20.3->PyTDC) (6.0.3)
Requirement already satisfied: biothings-client>=0.2.6 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from mygene<4.0.0,>=3.2.2->PyTDC) (0.5.1)
Requirement already satisfied: et-xmlfile in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from openpyxl<4.0.0,>=3.0.10->PyTDC) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from pandas<3.0.0,>=2.1.4->PyTDC) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from pandas<3.0.0,>=2.1.4->PyTDC) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from pandas<3.0.0,>=2.1.4->PyTDC) (2026.4)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.6.3->PyTDC) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.6.3->PyTDC) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.6.3->PyTDC) (0.4.4)
Requirement already satisfied: Pillow in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from rdkit<2024.3.1,>=2023.9.5->PyTDC) (12.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from requests<3.0.0,>=2.31.0->PyTDC) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from requests<3.0.0,>=2.31.0->PyTDC) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from requests<3.0.0,>=2.31.0->PyTDC) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from requests<3.0.0,>=2.31.0->PyTDC) (2026.7.22)
Requirement already satisfied: attrs>=22.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from tiledbsoma<2.0.0,>=1.7.2->PyTDC) (26.1.0)
Requirement already satisfied: more-itertools in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from tiledbsoma<2.0.0,>=1.7.2->PyTDC) (11.1.0)
Requirement already satisfied: pyarrow in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from tiledbsoma<2.0.0,>=1.7.2->PyTDC) (26.0.0)
Requirement already satisfied: scanpy>=1.9.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from tiledbsoma<2.0.0,>=1.7.2->PyTDC) (1.11.5)
Requirement already satisfied: somacore==1.0.28 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from tiledbsoma<2.0.0,>=1.7.2->PyTDC) (1.0.28)
Requirement already satisfied: pyarrow-hotfix in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from somacore==1.0.28->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (0.7)
Requirement already satisfied: shapely in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from somacore==1.0.28->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (2.2.0)
Requirement already satisfied: platformdirs>=3.5.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from yapf<1.0.0,>=0.40.2->PyTDC) (4.12.0)
Requirement already satisfied: array-api-compat>=1.7.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.15.0)
Requirement already satisfied: h5py>=3.8 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (3.16.0)
Requirement already satisfied: legacy-api-wrap in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.5)
Requirement already satisfied: natsort in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (8.4.0)
Requirement already satisfied: scverse-misc>=0.0.3 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (0.1.6)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (3.1.5)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from beautifulsoup4>=4.10->gget<1.0.0,>=0.28.4->PyTDC) (2.10)
Requirement already satisfied: httpx<1.0,>=0.25.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from biothings-client>=0.2.6->mygene<4.0.0,>=3.2.2->PyTDC) (0.28.1)
Requirement already satisfied: anyio in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from httpx<1.0,>=0.25.0->biothings-client>=0.2.6->mygene<4.0.0,>=3.2.2->PyTDC) (4.15.1)
Requirement already satisfied: httpcore==1.* in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from httpx<1.0,>=0.25.0->biothings-client>=0.2.6->mygene<4.0.0,>=3.2.2->PyTDC) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0,>=0.25.0->biothings-client>=0.2.6->mygene<4.0.0,>=3.2.2->PyTDC) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from joblib>=1.1.1->scikit-learn==1.2.2->PyTDC) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from matplotlib->gget<1.0.0,>=0.28.4->PyTDC) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from matplotlib->gget<1.0.0,>=0.28.4->PyTDC) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from matplotlib->gget<1.0.0,>=0.28.4->PyTDC) (4.66.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from matplotlib->gget<1.0.0,>=0.28.4->PyTDC) (1.5.1)
Requirement already satisfied: pyparsing>=3 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from matplotlib->gget<1.0.0,>=0.28.4->PyTDC) (3.3.3)
Requirement already satisfied: six>=1.5 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.1.4->PyTDC) (1.17.0)
Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (3.9.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (3.14.4)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (0.13.0)
Requirement already satisfied: botocore<1.43.107,>=1.43.101 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.43.106)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.1.0)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (6.9.1)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (2.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.8.0)
Requirement already satisfied: propcache>=0.2.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2021.06.1->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.25.1)
Requirement already satisfied: networkx>=2.7.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (2.8.8)
Requirement already satisfied: numba!=0.62.0rc1,>=0.57.1 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (0.68.0)
Requirement already satisfied: patsy!=1.0.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (1.0.3)
Requirement already satisfied: pynndescent>=0.5.13 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (0.6.0)
Requirement already satisfied: session-info2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (0.4.2)
Requirement already satisfied: statsmodels>=0.14.5 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (0.15.0)
Requirement already satisfied: umap-learn>=0.5.6 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (0.5.7)
Requirement already satisfied: llvmlite<0.51,>=0.50.0dev0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from numba!=0.62.0rc1,>=0.57.1->scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (0.50.0)
Requirement already satisfied: formulaic>=1.1.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from statsmodels>=0.14.5->scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from formulaic>=1.1.0->statsmodels>=0.14.5->scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from formulaic>=1.1.0->statsmodels>=0.14.5->scanpy>=1.9.2->tiledbsoma<2.0.0,>=1.7.2->PyTDC) (2.26.0)
Requirement already satisfied: donfig>=0.8 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from zarr!=3.0.*,>=2.18.7->anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from zarr!=3.0.*,>=2.18.7->anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (1.9.0)
Requirement already satisfied: numcodecs>=0.14 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from zarr!=3.0.*,>=2.18.7->anndata->cellxgene-census<2.0.0,>=1.10.2->PyTDC) (0.16.5)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (3.0.53)
Requirement already satisfied: psutil>=7 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from ipython->gget<1.0.0,>=0.28.4->PyTDC) (5.16.1)
Requirement already satisfied: wcwidth>=0.1.4 in /Users/reginaseca/miniforge3/envs/psl/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->gget<1.0.0,>=0.28.4->PyTDC) (0.9.1)

In [10]:

from tdc.single_pred import ADME, Tox
import pandas as pd

#Save dataset in "data"
raw_dir = Path("../ data / raw")
raw_dir.mkdir(parents=True, exist_ok=True)

# Load regression dataset
solubility = ADME(name="Solubility_AqSolDB")
df_reg = solubility.get_data()

# Load classification dataset 
herg = Tox(name="hERG")
df_clf = herg.get_data()

# First lines
display(df_reg.head(10))
display(df_clf.head(10))

#datasets shape
print("Classification :", df_clf.shape)

Found local copy...
Loading...
Done!
Found local copy...
Loading...
Done!

,Drug_ID,Drug,Y
0,"N,N,N-trimethyloctadecan-1-aminium bromide",CCCCCCCCCCCCCCCCCC[N+](C)(C)C.[Br-],-3.616127
1,Benzo[cd]indol-2(1H)-one,O=C1Nc2cccc3cccc1c23,-3.254767
2,4-chlorobenzaldehyde,O=Cc1ccc(Cl)cc1,-2.177078
3,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",CC(c1ccccc1)c1cc(C(=O)[O-])c(O)c(C(C)c2ccccc2)...,-3.924409
4,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,c1cc(N(CC2CO2)CC2CO2)ccc1Cc1ccc(N(CC2CO2)CC2CO...,-4.662065
5,vinyltoluene,C=Cc1cccc(C)c1,-3.123150
6,3-(3-ethylcyclopentyl)propanoic acid,CCC1CCC(CCC(=O)O)C1,-3.286116
7,"11,16,17,21-tetrahydroxypregna-1,4-diene-3,20-...",CC12C=CC(=O)C=C1CCC1C2C(O)CC2(C)C1CC(O)C2(O)C(...,-2.664549
8,bis(4-fluorophenyl)methanone,O=C(c1ccc(F)cc1)c1ccc(F)cc1,-4.396652
9,1-[2-(benzoyloxy)propoxy]propan-2-yl benzoate ...,O=C(OCCCOCCCOC(=O)c1ccccc1)c1ccccc1,-4.595503

,Drug_ID,Drug,Y
0,DEMETHYLASTEMIZOLE,Oc1ccc(CCN2CCC(Nc3nc4ccccc4n3Cc3ccc(F)cc3)CC2)cc1,1.0
1,GBR-12909,Fc1ccc(C(OCC[NH+]2CC[NH+](CCCc3ccccc3)CC2)c2cc...,1.0
2,LY-97241,CCCCCCCN(CC)CCCCc1ccc([N+](=O)[O-])cc1,1.0
3,CLOFILIUM PHOSPHATE,CCCCCCC[N+](CC)(CC)CCCCc1ccc(Cl)cc1.CCCCCCC[N+...,1.0
4,FLUSPIRILENE,O=C1NCN(c2ccccc2)C12CC[NH+](CCCC(c1ccc(F)cc1)c...,1.0
5,BENPERIDOL,O=C(CCCN1CCC(n2c(=O)[nH]c3ccccc32)CC1)c1ccc(F)cc1,1.0
6,NaN,Fc1ccc(-n2cc(C3CCN(CCN4CCNC4=S)CC3)c3ccccc32)cc1,1.0
7,BMCL20031829_03,O=C1NCCN1CCN1CCC(c2cn(-c3ccc(F)cc3)c3ccccc23)CC1,1.0
8,VANOXERINE HYDROCHLORIDE,Fc1ccc(C(OCCN2CCN(CCCc3ccccc3)CC2)c2ccc(F)cc2)cc1,1.0
9,L-691121,CS(=O)(=O)Nc1ccc2c(c1)C(=O)CC1(CCN(CCc3ccc4non...,1.0

Classification : (655, 3)